---
# These tasks are responsible for configuring Apache

- name: Apache | Include project variables
  include_vars: "{{ project_vars }}"

- name: Apache | Create virtualhost file
  template: src="{{ apache_virtualhost }}" dest="/etc/httpd/conf.d/{{ project_name }}.conf" owner=root group=root mode=0644
  notify: restart httpd
  when: apache_virtualhost|lower != "none"
