---
# This playbook deploys a project to a specific web server, database server, and backup server

# Gather information about the project, is this the first deploy? Or does it already exist?

- name: example project webserver
  hosts: "{{ webserver }}"
  remote_user: ansible
  sudo: yes
  roles:
    - files_status

# Restore files from backup server if any exist

- name: example project backup server
  hosts: backupservers
  remote_user: ansible
  sudo: yes
  roles:
    - files_restore
    - mysql_restore
  vars:
    - project_path: "/local/path/to/project-files"
    - project_vars: "{{ project_path }}/setup/variables.yml"

# Update setup webserver and sync project files

- name: example project webserver
  hosts: "{{ webserver }}"
  remote_user: ansible
  sudo: yes
  roles:
    - files_deploy
    - apache
  vars:
    - project_path: "/local/path/to/project-files"
    - project_vars: "{{ project_path }}/setup/variables.yml"
