---
# This playbook installs MySQL and sets up the project database and database users

- name: MySQL Deploy | Include project variables
  include_vars: "{{ project_vars }}"

- name: MySQL Deploy | Make sure MySQL is running
  service: name=mysqld state=started enabled=true

- name: MySQL Deploy | Create databases
  mysql_db: name={{ item.key }} state=present
  with_dict: mysql

- name: MySQL Deploy | Add database restore script
  copy: src=mysqlimport.sh dest=/var/lib/mysql/mysqlimport.sh owner=root group=root mode=0700

- name: MySQL Deploy | Import database data if needed
  shell: "/var/lib/mysql/mysqlimport.sh {{ item.key }} {{ project_name }}"
  with_dict: mysql

- name: MySQL Deploy | Create user with remote permissions
  mysql_user: name={{ item.value.username }} password={{ item.value.password }} priv="{{ item.key }}.*:ALL" host='%' state=present
  with_dict: mysql

- name: MySQL Deploy | Create user with localhost permissions
  mysql_user: name={{ item.value.username }} password={{ item.value.password }} priv="{{ item.key }}.*:ALL" host='localhost' state=present
  with_dict: mysql
