---
# Deploy the latest project repository files if it exists
  
- name: Files Deploy | Include project variables
  include_vars: "{{ project_vars }}"

- name: Files Deploy | Transfer repo files
  synchronize: src="{{ project_path }}/" dest="/var/www/{{ project_name }}"

- name: Files Deploy | Update file ownership
  shell: "chown -R apache:apache /var/www/{{ project_name }}"

- name: Files Deploy | Update directory permissions
  shell: "find /var/www/{{ project_name }} -type d -print0 | xargs -0 -I {} chmod 0755 {}"

- name: Files Deploy | Update file permissions
  shell: "find /var/www/{{ project_name }} -type f -print0 | xargs -0 -I {} chmod 0644 {}"

- name: Files Deploy | Update setup file permissions if they exist
  shell: "cd /var/www/{{ project_name }} && if [[ -f {{ item }} ]]; then chmod u+x {{ item }}; else exit 0; fi;"
  with_items:
    - setup
    - setup.sh
    - setup.py
    - setup.php
    - install
    - install.sh
    - install.py
    - install.php

- name: Files Deploy | Execute setup files if they exist
  shell: "cd /var/www/{{ project_name }} && if [[ -f {{ item }} ]]; then ./{{ item }}; else exit 0; fi;"
  with_items:
    - setup
    - setup.sh
    - setup.py
    - setup.php
    - install
    - install.sh
    - install.py
    - install.php

- name: Files Deploy | Touch WSGI file if it exists
  shell: "find /var/www/{{ project_name }} -type f -iname '*.wsgi' | xargs -I {} touch {}"
